### ISSUE TITLE
This theme is run github pages? 

### ISSUE THREAD

**Issue by rudehe** [renyuanz/leonids#27]

**Comment by renyuanz** [comment]
[This project](https://renyuanz.github.io/leonids/) and [my personal blog ](http://renyuanz.github.io/) are running github pages.

**Comment by renyuanz** [comment]
In the case you want ask me something else, I'll leave it open.

**Comment by rudehe** [comment]
Thank you!
I use this theme for my blog in github pages

step1. Fork repo ... ok
step2. change name User.github.io ... ok
step3. post modified ... **do not**
step4. new post write ... **do not**  (I use prose.io)

what can i do to solve this problem?

**Comment by renyuanz** [comment]
Sorry for not providing a doc.

I just checked your blog repo, and I think the problem is missing a [front matter](https://jekyllrb.com/docs/frontmatter) for your own posts.

You need to provide a front matter for each post file

```yml
---
layout: post
title: Sample Post
excerpt: "Just about everything you'll need to style in the theme: headings, paragraphs, blockquotes, tables, code blocks, and more."
categories: [hello world]
comments: true
image:
  feature: https://images.unsplash.com/photo-1440635592348-167b1b30296f?crop=entropy&dpr=2&fit=crop&fm=jpg&h=475&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1250
  credit: thomas shellberg
  creditlink: https://unsplash.com/photos/Ki0dpxd3LGc
---
```

And, I noticed that you added a `published: true / false` in the front matter and I suppose you are testing that. Actually, `published` is not using and is causing a building failure. Try to avoid using unknown key/value in the front matter.

If you want make a `draft` post, you can make a folder named `_draft` to store them temporally.

Hope this helps.
