### ISSUE TITLE
jekyll-paginate is not supported

### ISSUE THREAD

**Issue by syhily** [renyuanz/leonids#65]
I want to have a pagination in index page

**Comment by geeknerd** [comment]
In my post-index.html (now I believe it's called post_listing.html) I added:
```
<ul class="pager"> 

  {% if paginator.previous_page %}
  <li class="previous">
    {% if paginator.previous_page == 1 %}
    <a href="{{ site.BASE_PATH }}/#blog">&larr; Newer</a>
    {% else %}
    <a href="{{ site.BASE_PATH }}/{{ site.paginate_path | replace: ':num', paginator.previous_page }}">&larr; Newer</a>
    {% endif %}
  </li>
  {% else %}
  <li class="previous disabled">
    <a>&larr; Newer</a>
  </li>
  {% endif %}
  
  <li>
    <span class="page_number">Page: {{ paginator.page }} of {{ paginator.total_pages }}</span>
  </li>

  {% if paginator.next_page %}
  <li class="next">
    <a href="{{ site.BASE_PATH }}/{{ site.paginate_path | replace: ':num', paginator.next_page }}">Older &rarr;</a>
  </li>
  {% else %}
  <li class="next disabled">
    <a>Older &rarr;</a>        
  </li>
  {% endif %}

</ul>
```

Might need some tweaks but the idea should be the same.

**Comment by syhily** [comment]
@geeknerd 
Cool, I also implement my own pagination.

```html
{% if paginator.total_pages > 1 %}
<nav class="pagination row">
  <ul class="pagination-list">
    <li class="pagination-icon"><i class="fa fa-th-list"></i></li>
    {% for page in (1..paginator.total_pages) %}
      {% if page == paginator.page %}
        <li class="current"><a href="javascript:void(0);">{{ page }}</a></li>
      {% else %}
        <li><a href="{{ site.url }}/{%if page > 1 %}page/{{ page }}/{% endif %}">{{ page }}</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endif %}
```

```scss
.pagination {
  line-height: 32px;
  padding-top: 20px;
}
.pagination li {
  float: left;
  margin: 0 10px 10px 0;
  list-style-type: none;
}
.pagination-icon {
  width: 32px;
  height: 32px;
  display: block;
  float: left;
  font-size: 16px;
  line-height: 32px;
  text-align: center;
  color: #fefefe;
  background: #99b9c4;
}
.pagination-list {
  padding-left: 0px;
  width: 550px;
  height: 32px;
  line-height: 32px;
  float: left;
}
.pagination-list li a {
  width: 32px;
  height: 32px;
  display: block;
  background: #f2eeec;
  text-align: center;
}
.pagination-list .current a {
  background: #e54e4d;
  color: #fefefe;
}
```
